/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii.tables.records;


import com.example.demo.infra.hawaii.tables.UserProfiles;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserProfilesRecord extends UpdatableRecordImpl<UserProfilesRecord> implements Record6<UUID, UUID, String, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -277867224;

    /**
     * Create a detached UserProfilesRecord
     */
    public UserProfilesRecord() {
        super(UserProfiles.USER_PROFILES);
    }

    /**
     * Create a detached, initialised UserProfilesRecord
     */
    public UserProfilesRecord(UUID id, UUID userId, String tel, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        super(UserProfiles.USER_PROFILES);

        set(0, id);
        set(1, userId);
        set(2, tel);
        set(3, createdAt);
        set(4, updatedAt);
        set(5, deletedAt);
    }

    /**
     * Getter for <code>public.user_profiles.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user_profiles.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_profiles.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.user_profiles.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_profiles.tel</code>.
     */
    public String getTel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_profiles.tel</code>.
     */
    public void setTel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_profiles.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.user_profiles.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_profiles.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.user_profiles.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>public.user_profiles.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>public.user_profiles.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(5, value);
    }

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    @Override
    public Row6<UUID, UUID, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, String, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UserProfiles.USER_PROFILES.ID;
    }

    @Override
    public Field<UUID> field2() {
        return UserProfiles.USER_PROFILES.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return UserProfiles.USER_PROFILES.TEL;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return UserProfiles.USER_PROFILES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserProfiles.USER_PROFILES.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserProfiles.USER_PROFILES.DELETED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getTel();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getDeletedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getTel();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getDeletedAt();
    }

    @Override
    public UserProfilesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UserProfilesRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserProfilesRecord value3(String value) {
        setTel(value);
        return this;
    }

    @Override
    public UserProfilesRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserProfilesRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public UserProfilesRecord value6(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public UserProfilesRecord values(UUID value1, UUID value2, String value3, LocalDateTime value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
}
