/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii.tables.daos;


import com.example.demo.infra.hawaii.tables.User;
import com.example.demo.infra.hawaii.tables.records.UserRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, com.example.demo.infra.hawaii.tables.pojos.User, UUID> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.example.demo.infra.hawaii.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, com.example.demo.infra.hawaii.tables.pojos.User.class, configuration);
    }

    @Override
    public UUID getId(com.example.demo.infra.hawaii.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(User.USER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchById(UUID... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.demo.infra.hawaii.tables.pojos.User fetchOneById(UUID value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public com.example.demo.infra.hawaii.tables.pojos.User fetchOneByUsername(String value) {
        return fetchOne(User.USER.USERNAME, value);
    }

    /**
     * Fetch records that have <code>password_hash BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfPasswordHash(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.PASSWORD_HASH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password_hash IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByPasswordHash(String... values) {
        return fetch(User.USER.PASSWORD_HASH, values);
    }

    /**
     * Fetch records that have <code>nickname BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfNickname(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.NICKNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>nickname IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByNickname(String... values) {
        return fetch(User.USER.NICKNAME, values);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByFirstName(String... values) {
        return fetch(User.USER.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByLastName(String... values) {
        return fetch(User.USER.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>authorities BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfAuthorities(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.AUTHORITIES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorities IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByAuthorities(String... values) {
        return fetch(User.USER.AUTHORITIES, values);
    }

    /**
     * Fetch records that have <code>is_enabled BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfIsEnabled(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(User.USER.IS_ENABLED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_enabled IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByIsEnabled(Boolean... values) {
        return fetch(User.USER.IS_ENABLED, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByEmail(String... values) {
        return fetch(User.USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>email_confirmed BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfEmailConfirmed(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(User.USER.EMAIL_CONFIRMED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email_confirmed IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByEmailConfirmed(Boolean... values) {
        return fetch(User.USER.EMAIL_CONFIRMED, values);
    }

    /**
     * Fetch records that have <code>phone_number BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfPhoneNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.PHONE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone_number IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByPhoneNumber(String... values) {
        return fetch(User.USER.PHONE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>phone_number_confirmed BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfPhoneNumberConfirmed(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(User.USER.PHONE_NUMBER_CONFIRMED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone_number_confirmed IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByPhoneNumberConfirmed(Boolean... values) {
        return fetch(User.USER.PHONE_NUMBER_CONFIRMED, values);
    }

    /**
     * Fetch records that have <code>two_factor_enabled BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfTwoFactorEnabled(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(User.USER.TWO_FACTOR_ENABLED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>two_factor_enabled IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByTwoFactorEnabled(Boolean... values) {
        return fetch(User.USER.TWO_FACTOR_ENABLED, values);
    }

    /**
     * Fetch records that have <code>lockout_end BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfLockoutEnd(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.LOCKOUT_END, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lockout_end IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByLockoutEnd(LocalDateTime... values) {
        return fetch(User.USER.LOCKOUT_END, values);
    }

    /**
     * Fetch records that have <code>lockout_enabled BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfLockoutEnabled(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(User.USER.LOCKOUT_ENABLED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lockout_enabled IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByLockoutEnabled(Boolean... values) {
        return fetch(User.USER.LOCKOUT_ENABLED, values);
    }

    /**
     * Fetch records that have <code>access_failed_count BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfAccessFailedCount(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(User.USER.ACCESS_FAILED_COUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>access_failed_count IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByAccessFailedCount(Integer... values) {
        return fetch(User.USER.ACCESS_FAILED_COUNT, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(User.USER.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(User.USER.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>deleted_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchRangeOfDeletedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.DELETED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted_at IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.User> fetchByDeletedAt(LocalDateTime... values) {
        return fetch(User.USER.DELETED_AT, values);
    }
}
