/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii.tables.daos;


import com.example.demo.infra.hawaii.tables.UserProfiles;
import com.example.demo.infra.hawaii.tables.records.UserProfilesRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.processing.Generated;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserProfilesDao extends DAOImpl<UserProfilesRecord, com.example.demo.infra.hawaii.tables.pojos.UserProfiles, UUID> {

    /**
     * Create a new UserProfilesDao without any configuration
     */
    public UserProfilesDao() {
        super(UserProfiles.USER_PROFILES, com.example.demo.infra.hawaii.tables.pojos.UserProfiles.class);
    }

    /**
     * Create a new UserProfilesDao with an attached configuration
     */
    public UserProfilesDao(Configuration configuration) {
        super(UserProfiles.USER_PROFILES, com.example.demo.infra.hawaii.tables.pojos.UserProfiles.class, configuration);
    }

    @Override
    public UUID getId(com.example.demo.infra.hawaii.tables.pojos.UserProfiles object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchById(UUID... values) {
        return fetch(UserProfiles.USER_PROFILES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.demo.infra.hawaii.tables.pojos.UserProfiles fetchOneById(UUID value) {
        return fetchOne(UserProfiles.USER_PROFILES.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfUserId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchByUserId(UUID... values) {
        return fetch(UserProfiles.USER_PROFILES.USER_ID, values);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchByFirstName(String... values) {
        return fetch(UserProfiles.USER_PROFILES.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchByLastName(String... values) {
        return fetch(UserProfiles.USER_PROFILES.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>birthday BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfBirthday(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.BIRTHDAY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>birthday IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchByBirthday(LocalDate... values) {
        return fetch(UserProfiles.USER_PROFILES.BIRTHDAY, values);
    }

    /**
     * Fetch records that have <code>tel BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfTel(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.TEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tel IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchByTel(String... values) {
        return fetch(UserProfiles.USER_PROFILES.TEL, values);
    }

    /**
     * Fetch records that have <code>sex BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfSex(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.SEX, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchBySex(Short... values) {
        return fetch(UserProfiles.USER_PROFILES.SEX, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(UserProfiles.USER_PROFILES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(UserProfiles.USER_PROFILES.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>deleted_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchRangeOfDeletedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.DELETED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted_at IN (values)</code>
     */
    public List<com.example.demo.infra.hawaii.tables.pojos.UserProfiles> fetchByDeletedAt(LocalDateTime... values) {
        return fetch(UserProfiles.USER_PROFILES.DELETED_AT, values);
    }
}
