version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: ducknet_postgres
    restart: always
    env_file: ./docker/postgresql.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    networks: [ default ]
volumes:
  postgres_data:
    driver: local
networks:
  default:
    name: ducknet
