/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii.tables.records;


import com.example.demo.infra.hawaii.tables.Memo;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemoRecord extends UpdatableRecordImpl<MemoRecord> implements Record7<UUID, UUID, String, String, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 142742737;

    /**
     * Setter for <code>public.memo.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.memo.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.memo.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.memo.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.memo.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.memo.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.memo.body</code>.
     */
    public void setBody(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.memo.body</code>.
     */
    public String getBody() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.memo.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.memo.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.memo.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.memo.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.memo.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.memo.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, UUID, String, String, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Memo.MEMO.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Memo.MEMO.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Memo.MEMO.TITLE;
    }

    @Override
    public Field<String> field4() {
        return Memo.MEMO.BODY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Memo.MEMO.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Memo.MEMO.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Memo.MEMO.DELETED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getBody();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getDeletedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getBody();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getDeletedAt();
    }

    @Override
    public MemoRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public MemoRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public MemoRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public MemoRecord value4(String value) {
        setBody(value);
        return this;
    }

    @Override
    public MemoRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MemoRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public MemoRecord value7(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public MemoRecord values(UUID value1, UUID value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemoRecord
     */
    public MemoRecord() {
        super(Memo.MEMO);
    }

    /**
     * Create a detached, initialised MemoRecord
     */
    public MemoRecord(UUID id, UUID userId, String title, String body, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        super(Memo.MEMO);

        set(0, id);
        set(1, userId);
        set(2, title);
        set(3, body);
        set(4, createdAt);
        set(5, updatedAt);
        set(6, deletedAt);
    }
}
