/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii.tables.records;


import com.example.demo.infra.hawaii.tables.UserProfile;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfileRecord extends UpdatableRecordImpl<UserProfileRecord> implements Record10<UUID, UUID, String, String, LocalDate, String, Short, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -474265169;

    /**
     * Setter for <code>public.user_profile.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_profile.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user_profile.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_profile.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.user_profile.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_profile.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_profile.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_profile.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_profile.birthday</code>.
     */
    public void setBirthday(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_profile.birthday</code>.
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.user_profile.tel</code>.
     */
    public void setTel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_profile.tel</code>.
     */
    public String getTel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user_profile.sex</code>.
     */
    public void setSex(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_profile.sex</code>.
     */
    public Short getSex() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.user_profile.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user_profile.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.user_profile.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user_profile.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.user_profile.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user_profile.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, UUID, String, String, LocalDate, String, Short, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, UUID, String, String, LocalDate, String, Short, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UserProfile.USER_PROFILE.ID;
    }

    @Override
    public Field<UUID> field2() {
        return UserProfile.USER_PROFILE.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return UserProfile.USER_PROFILE.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return UserProfile.USER_PROFILE.LAST_NAME;
    }

    @Override
    public Field<LocalDate> field5() {
        return UserProfile.USER_PROFILE.BIRTHDAY;
    }

    @Override
    public Field<String> field6() {
        return UserProfile.USER_PROFILE.TEL;
    }

    @Override
    public Field<Short> field7() {
        return UserProfile.USER_PROFILE.SEX;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return UserProfile.USER_PROFILE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return UserProfile.USER_PROFILE.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return UserProfile.USER_PROFILE.DELETED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public LocalDate component5() {
        return getBirthday();
    }

    @Override
    public String component6() {
        return getTel();
    }

    @Override
    public Short component7() {
        return getSex();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getDeletedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public LocalDate value5() {
        return getBirthday();
    }

    @Override
    public String value6() {
        return getTel();
    }

    @Override
    public Short value7() {
        return getSex();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getDeletedAt();
    }

    @Override
    public UserProfileRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UserProfileRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserProfileRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserProfileRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserProfileRecord value5(LocalDate value) {
        setBirthday(value);
        return this;
    }

    @Override
    public UserProfileRecord value6(String value) {
        setTel(value);
        return this;
    }

    @Override
    public UserProfileRecord value7(Short value) {
        setSex(value);
        return this;
    }

    @Override
    public UserProfileRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserProfileRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UserProfileRecord value10(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public UserProfileRecord values(UUID value1, UUID value2, String value3, String value4, LocalDate value5, String value6, Short value7, LocalDateTime value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfileRecord
     */
    public UserProfileRecord() {
        super(UserProfile.USER_PROFILE);
    }

    /**
     * Create a detached, initialised UserProfileRecord
     */
    public UserProfileRecord(UUID id, UUID userId, String firstName, String lastName, LocalDate birthday, String tel, Short sex, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        super(UserProfile.USER_PROFILE);

        set(0, id);
        set(1, userId);
        set(2, firstName);
        set(3, lastName);
        set(4, birthday);
        set(5, tel);
        set(6, sex);
        set(7, createdAt);
        set(8, updatedAt);
        set(9, deletedAt);
    }
}
