server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hawaii}
    username: ${SPRING_DATASOURCE_USERNAME:rockman}
    password: ${SPRING_DATASOURCE_PASSWORD:mokuren}
  flyway:
    enabled: false
    baseline-on-migrate: true
  quartz:
    job-store-type: memory
    jdbc:
      initialize-schema: always
  jooq:
    sql-dialect: postgres

logging:
  level.org.springframework.data.jdbc: DEBUG

org:
  jooq:
    no-logo: true
