/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii;


import com.example.demo.infra.hawaii.tables.Memos;
import com.example.demo.infra.hawaii.tables.UserProfiles;
import com.example.demo.infra.hawaii.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.memos</code>.
     */
    public static final Memos MEMOS = Memo.MEMO;

    /**
     * The table <code>public.user_profiles</code>.
     */
    public static final UserProfiles USER_PROFILES = UserProfiles.USER_PROFILES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = User.USER;
}
