/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii.tables.pojos;


import javax.annotation.processing.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Users implements Serializable {

    private static final long serialVersionUID = 842226345;

    private UUID id;
    private String username;
    private String passwordHash;
    private String nickname;
    private String firstName;
    private String lastName;
    private String authorities;
    private Boolean isEnabled;
    private String email;
    private Boolean emailConfirmed;
    private String phoneNumber;
    private Boolean phoneNumberConfirmed;
    private Boolean twoFactorEnabled;
    private LocalDateTime lockoutEnd;
    private Boolean lockoutEnabled;
    private Integer accessFailedCount;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Users() {
    }

    public Users(Users value) {
        this.id = value.id;
        this.username = value.username;
        this.passwordHash = value.passwordHash;
        this.nickname = value.nickname;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.authorities = value.authorities;
        this.isEnabled = value.isEnabled;
        this.email = value.email;
        this.emailConfirmed = value.emailConfirmed;
        this.phoneNumber = value.phoneNumber;
        this.phoneNumberConfirmed = value.phoneNumberConfirmed;
        this.twoFactorEnabled = value.twoFactorEnabled;
        this.lockoutEnd = value.lockoutEnd;
        this.lockoutEnabled = value.lockoutEnabled;
        this.accessFailedCount = value.accessFailedCount;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.deletedAt = value.deletedAt;
    }

    public Users(
            UUID id,
            String username,
            String passwordHash,
            String nickname,
            String firstName,
            String lastName,
            String authorities,
            Boolean isEnabled,
            String email,
            Boolean emailConfirmed,
            String phoneNumber,
            Boolean phoneNumberConfirmed,
            Boolean twoFactorEnabled,
            LocalDateTime lockoutEnd,
            Boolean lockoutEnabled,
            Integer accessFailedCount,
            LocalDateTime createdAt,
            LocalDateTime updatedAt,
            LocalDateTime deletedAt
    ) {
        this.id = id;
        this.username = username;
        this.passwordHash = passwordHash;
        this.nickname = nickname;
        this.firstName = firstName;
        this.lastName = lastName;
        this.authorities = authorities;
        this.isEnabled = isEnabled;
        this.email = email;
        this.emailConfirmed = emailConfirmed;
        this.phoneNumber = phoneNumber;
        this.phoneNumberConfirmed = phoneNumberConfirmed;
        this.twoFactorEnabled = twoFactorEnabled;
        this.lockoutEnd = lockoutEnd;
        this.lockoutEnabled = lockoutEnabled;
        this.accessFailedCount = accessFailedCount;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswordHash() {
        return this.passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAuthorities() {
        return this.authorities;
    }

    public void setAuthorities(String authorities) {
        this.authorities = authorities;
    }

    public Boolean getIsEnabled() {
        return this.isEnabled;
    }

    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getEmailConfirmed() {
        return this.emailConfirmed;
    }

    public void setEmailConfirmed(Boolean emailConfirmed) {
        this.emailConfirmed = emailConfirmed;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Boolean getPhoneNumberConfirmed() {
        return this.phoneNumberConfirmed;
    }

    public void setPhoneNumberConfirmed(Boolean phoneNumberConfirmed) {
        this.phoneNumberConfirmed = phoneNumberConfirmed;
    }

    public Boolean getTwoFactorEnabled() {
        return this.twoFactorEnabled;
    }

    public void setTwoFactorEnabled(Boolean twoFactorEnabled) {
        this.twoFactorEnabled = twoFactorEnabled;
    }

    public LocalDateTime getLockoutEnd() {
        return this.lockoutEnd;
    }

    public void setLockoutEnd(LocalDateTime lockoutEnd) {
        this.lockoutEnd = lockoutEnd;
    }

    public Boolean getLockoutEnabled() {
        return this.lockoutEnabled;
    }

    public void setLockoutEnabled(Boolean lockoutEnabled) {
        this.lockoutEnabled = lockoutEnabled;
    }

    public Integer getAccessFailedCount() {
        return this.accessFailedCount;
    }

    public void setAccessFailedCount(Integer accessFailedCount) {
        this.accessFailedCount = accessFailedCount;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(nickname);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(authorities);
        sb.append(", ").append(isEnabled);
        sb.append(", ").append(email);
        sb.append(", ").append(emailConfirmed);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(phoneNumberConfirmed);
        sb.append(", ").append(twoFactorEnabled);
        sb.append(", ").append(lockoutEnd);
        sb.append(", ").append(lockoutEnabled);
        sb.append(", ").append(accessFailedCount);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(deletedAt);

        sb.append(")");
        return sb.toString();
    }
}
