/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii;


import com.example.demo.infra.hawaii.tables.FlywaySchemaHistory;
import com.example.demo.infra.hawaii.tables.Memos;
import com.example.demo.infra.hawaii.tables.UserProfiles;
import com.example.demo.infra.hawaii.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();
    private static final long serialVersionUID = 68655644;
    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.example.demo.infra.hawaii.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.memos</code>.
     */
    public final Memos MEMOS = com.example.demo.infra.hawaii.tables.Memos.MEMOS;

    /**
     * The table <code>public.user_profiles</code>.
     */
    public final UserProfiles USER_PROFILES = com.example.demo.infra.hawaii.tables.UserProfiles.USER_PROFILES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.example.demo.infra.hawaii.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
                Memos.MEMOS,
                UserProfiles.USER_PROFILES,
                Users.USERS);
    }
}
