/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii;


import com.example.demo.infra.hawaii.tables.FlywaySchemaHistory;
import com.example.demo.infra.hawaii.tables.Memo;
import com.example.demo.infra.hawaii.tables.User;
import com.example.demo.infra.hawaii.tables.UserProfile;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -81471262;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.example.demo.infra.hawaii.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.memo</code>.
     */
    public final Memo MEMO = com.example.demo.infra.hawaii.tables.Memo.MEMO;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = com.example.demo.infra.hawaii.tables.User.USER;

    /**
     * The table <code>public.user_profile</code>.
     */
    public final UserProfile USER_PROFILE = com.example.demo.infra.hawaii.tables.UserProfile.USER_PROFILE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Memo.MEMO,
            User.USER,
            UserProfile.USER_PROFILE);
    }
}
