/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infra.hawaii;


import com.example.demo.infra.hawaii.tables.FlywaySchemaHistory;
import com.example.demo.infra.hawaii.tables.Memo;
import com.example.demo.infra.hawaii.tables.User;
import com.example.demo.infra.hawaii.tables.UserProfile;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.memo</code>.
     */
    public static final Memo MEMO = Memo.MEMO;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_profile</code>.
     */
    public static final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;
}
